ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.zioanacleto.feedtracker.ApplicationKt.module ]
    }
}

database {
    driver = "org.postgresql.Driver"
    url = ${?DATABASE_URL}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = ${?DATABASE_MAX_POOL_SIZE}
}
